### ISSUE TITLE
Not available on Hackage

### ISSUE THREAD

**Issue by edouardpoitras** [jdreaver/oanda-rest-api#1]
Hello,

I'm wondering if you had any plans to add this library to hackage.  Being able to add it as a dependency to my projects in my cabal file would be convenient :)

**Comment by jdreaver** [comment]
Hey! My original plan was to finish the API before uploading to Hackage, but I have enough of the API implemented to already be useful useful. I can upload it sometime today.

Note that I don't use the library in my projects yet. Once I do (which should be in a few months), then I'll fully commit to keeping it up to date and making totally sure there aren't bugs.

**Comment by jdreaver** [comment]
I've uploaded it to Hackage. Check it out!

https://hackage.haskell.org/package/oanda-rest-api

**Comment by edouardpoitras** [comment]
Thanks a lot John! I appreciate the work on this.
