### ISSUE TITLE
Build failure with GHC 7.8

### ISSUE THREAD

**Issue by hvr** [jdreaver/oanda-rest-api#4]
The cabal file claims to be compatible with base-4.7, but GHC disagrees:

```
Configuring component lib from oanda-rest-api-0.3.0.0
Preprocessing library oanda-rest-api-0.3.0.0...
[ 1 of 12] Compiling OANDA.Internal.Import ( src/OANDA/Internal/Import.hs, /tmp/matrix-worker/1480188505/dist-newstyle/build/x86_64-linux/ghc-7.8.4/oanda-rest-api-0.3.0.0/build/OANDA/Internal/Import.o )
[ 2 of 12] Compiling OANDA.Internal.Types ( src/OANDA/Internal/Types.hs, /tmp/matrix-worker/1480188505/dist-newstyle/build/x86_64-linux/ghc-7.8.4/oanda-rest-api-0.3.0.0/build/OANDA/Internal/Types.o )

src/OANDA/Internal/Types.hs:67:41: Not in scope: ‘pure’
```

**Comment by jdreaver** [comment]
Ah I totally forgot about version bounds on `base`. I'll increase the minimum `base` version. Thanks!

**Comment by jdreaver** [comment]
Fixed via https://github.com/jdreaver/oanda-rest-api/commit/fda9a2b6f4967454eb9f48fddbdf47912dec9ebb

**Comment by hvr** [comment]
Fyi, I've also fixed up the meta-data at https://hackage.haskell.org/package/oanda-rest-api-0.3.0.0/revisions/ to prevent cabal picking such a bad install-plan.

**Comment by jdreaver** [comment]
Awesome, thanks!

**Comment by hvr** [comment]
you're welcome! :-)
