### ISSUE TITLE
Submit version 0.4.0.0 to Hackage

### ISSUE THREAD

**Issue by tysonzero** [jdreaver/oanda-rest-api#8]
Unfortunately this is not something I can do with a PR or anything like that, but it would really make my life easier if 0.4.0.0 was on hackage and stackage. Since 0.3.0.0 is not really usable for trading.

**Comment by jdreaver** [comment]
Done.

For the future, did you know you can add projects from github via `stack.yaml`? See [this](https://stackoverflow.com/questions/38377521/haskell-stack-install-dependency-from-github) stackoverflow question for how.
